# Imports

In [2]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv("df_filtered.csv")
df

               pre_root_id        post_root_id  neuropil  syn_count nt_type
0       720575940613501855  720575940614026193   MB_VL_R          6     ACH
1       720575940627700484  720575940613583001  MB_PED_R          1     ACH
2       720575940628259914  720575940613583001     SCL_R          5     ACH
3       720575940627590421  720575940622987912   MB_VL_L          4     ACH
4       720575940622791429  720575940617643072   MB_VL_L          1     ACH
...                    ...                 ...       ...        ...     ...
242393  720575940613583001  720575940615134918  MB_PED_R          1    GABA
242394  720575940613197608  720575940624547622     CRE_L          2     ACH
242395  720575940634819167  720575940612783218   MB_CA_L          3     ACH
242396  720575940628119555  720575940617302365   MB_VL_L          4     ACH
242397  720575940621521663  720575940620975696  MB_PED_L          1     ACH

[242398 rows x 5 columns]

In [5]:
df['neuropil'].unique()

array(['MB_VL_R', 'MB_PED_R', 'SCL_R', 'MB_VL_L', 'CRE_L', 'MB_PED_L',
       'MB_ML_L', 'MB_CA_L', 'MB_CA_R', 'MB_ML_R', 'ICL_R', 'SIP_L',
       'LAL_R', 'CRE_R', 'SMP_L', 'SLP_R', 'SIP_R', 'SMP_R', 'SCL_L',
       'PLP_L', 'PLP_R', 'LAL_L', 'ICL_L', 'EB', 'SLP_L', 'PB', 'IB_R',
       'LH_L', 'GOR_R', 'LH_R'], dtype=object)

In [6]:
df['nt_type'].unique()

array(['ACH', 'GABA', 'GLUT', 'DA', 'OCT', 'SER'], dtype=object)

In [7]:
special_ids = [720575940613583001, 720575940624547622]

MB_regions = [
    "MB_CA_L",   # Calyx, left hemisphere (input)
    "MB_CA_R",   # Calyx, right hemisphere (input)
    "MB_PED_L",  # Pedunculus, left hemisphere (stalk)
    "MB_PED_R",  # Pedunculus, right hemisphere (stalk)
    "MB_VL_L",   # Vertical lobe, left hemisphere (output)
    "MB_VL_R",   # Vertical lobe, right hemisphere (output)
    "MB_ML_L",   # Medial lobe, left hemisphere (output)
    "MB_ML_R"    # Medial lobe, right hemisphere (output)
]

In [8]:
# Filter: either neuropil is MB or pre/post root ID matches one of the special IDs
df_filtered = df[
    df['neuropil'].isin(MB_regions) |
    df['pre_root_id'].isin(special_ids) |
    df['post_root_id'].isin(special_ids)
]
df_filtered

               pre_root_id        post_root_id  neuropil  syn_count nt_type
0       720575940613501855  720575940614026193   MB_VL_R          6     ACH
1       720575940627700484  720575940613583001  MB_PED_R          1     ACH
2       720575940628259914  720575940613583001     SCL_R          5     ACH
3       720575940627590421  720575940622987912   MB_VL_L          4     ACH
4       720575940622791429  720575940617643072   MB_VL_L          1     ACH
...                    ...                 ...       ...        ...     ...
242393  720575940613583001  720575940615134918  MB_PED_R          1    GABA
242394  720575940613197608  720575940624547622     CRE_L          2     ACH
242395  720575940634819167  720575940612783218   MB_CA_L          3     ACH
242396  720575940628119555  720575940617302365   MB_VL_L          4     ACH
242397  720575940621521663  720575940620975696  MB_PED_L          1     ACH

[242398 rows x 5 columns]

In [9]:
# Export filtered DataFrame to CSV
df_filtered.to_csv("df_filtered_MB_connections.csv", index=False)

In [10]:
df[
    df['neuropil'].isin(['CRE_L'])
]

               pre_root_id        post_root_id neuropil  syn_count nt_type
5       720575940626782845  720575940624547622    CRE_L          1     ACH
99      720575940621812006  720575940624547622    CRE_L          7     ACH
107     720575940619146837  720575940624547622    CRE_L         10     ACH
172     720575940624547622  720575940610862506    CRE_L          2    GABA
249     720575940624547622  720575940614605458    CRE_L          2    GABA
...                    ...                 ...      ...        ...     ...
242297  720575940624547622  720575940624243982    CRE_L          3    GABA
242303  720575940617567390  720575940624547622    CRE_L          4     ACH
242330  720575940629803264  720575940624547622    CRE_L          1     ACH
242335  720575940624547622  720575940639013210    CRE_L          1    GABA
242394  720575940613197608  720575940624547622    CRE_L          2     ACH

[4054 rows x 5 columns]

In [11]:
df[
    df['neuropil'].isin(['CRE_R'])
]

               pre_root_id        post_root_id neuropil  syn_count nt_type
118     720575940613583001  720575940623582904    CRE_R          2    GABA
119     720575940632019247  720575940613583001    CRE_R          6     ACH
136     720575940613583001  720575940607330499    CRE_R          1    GABA
230     720575940627426837  720575940613583001    CRE_R          2     ACH
268     720575940613583001  720575940620418774    CRE_R          3    GABA
...                    ...                 ...      ...        ...     ...
242317  720575940632111780  720575940613583001    CRE_R          1     ACH
242321  720575940613583001  720575940621947486    CRE_R          2    GABA
242326  720575940614447922  720575940613583001    CRE_R          2     ACH
242342  720575940614861974  720575940613583001    CRE_R          2     ACH
242371  720575940613583001  720575940622216009    CRE_R          3    GABA

[3757 rows x 5 columns]